project_id = "nuyrzdpbmojbiqjtaphu"

[functions.send-reclamo-email]
verify_jwt = false

[functions.create-mercadopago-preference]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-contract-email]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.download-contract]
verify_jwt = false
